apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-to-kafka-with-timestamp-router
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-not-secured-source
    properties:
      bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
      topic: 'test-topic'
  steps:
  -  ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timestamp-router-action
    properties:
      topicFormat: '$[topic]_$[timestamp]'
      timestampFormat: 'YYYY-MM-dd'
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-not-secured-sink
    properties:
      bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
      topic: 'test-topic-2'
