#
# Apache Camel AWS Kinesis Source
#
apiVersion: sources.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-aws-sqs-source
spec:
  source:
    integration:
      configuration:
        - type: secret
          value: aws-sqs
      dependencies:
        # Needed for the json part on the flow/steps below
        - camel:jackson
        # Needed for the AWS Kinesis component
        - camel:camel-aws2-sqs
    flow:
      from:
        # On the URI below, the Kinesis stream named 'stream' can be adjusted
        # to any value suitable in your scenario (ie.: aws-sqs:my-stream-name)
        uri: aws2-sqs:eventqueue
        parameters:
          secretKey: "{{aws.sqs.secretKey}}"
          accessKey: "{{aws.sqs.accessKey}}"
          region: "{{aws.sqs.region}}"
          deleteAfterRead: "false"
        steps:
        - to: "log:received?showAll=true&multiline=true"
        - marshal:
            json: {}
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: InMemoryChannel
      name: aws-sqs
